### ISSUE TITLE
Next line charcaters (and others, like emoticons) are appended to links, making them invalid

### ISSUE THREAD

**Issue by JaapMoolenaar** [Happening/Chat#2]
If I were to type the following message:

```
See link:
http://lmgtfy.com/?q=Happening
:-)
```

Then the next line character (parsed into a &amp;lt;br&amp;gt;) and the emoticon are concatenated, creating this link:

```
http://lmgtfy.com/?q=Happening&lt;br&gt;😄
```

Which is invalid, and as such, will not even open the browser.

**Comment by vanviegen** [comment]
Thanks, fixed! (updated lazily, restart the app twice to see it.)

**Comment by JaapMoolenaar** [comment]
Works nicely thanks!
